version: "3.7"
services:
  muckr-api-nginx:
    build: ./nginx
    ports:
      - 9000:80
  muckr-api:
    build: .
    env_file: .env
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
  postgres:
    image: postgres:11.2-alpine
    env_file: .env
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database:
