version: "3.7"
services:
  postgres:
    image: postgres:11.2-alpine
    env_file: .env
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    ports:
      - "8080:8080"
volumes:
  database:
