version: '3.1'
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    env_file: .env
    volumes:
      - muckr-database:/var/lib/postgresql/data
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  adminer:
    image: adminer
    ports:
      - 8080:8080
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
volumes:
  muckr-database:
